AllCops:
  TargetRubyVersion: 2.4

  Exclude:
    - 'vendor/bundle/**/*'

  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15
