language: ruby

rvm:
  - 2.4.6
  - 2.5.5
  - ruby-head

before_install:
  - gem install bundler
  - rm -f .git/index.lock

script: "bundle exec rake spec:with_coveralls"

notifications:
  email: false
  slack: sachin21dev:3pEyff2UFnoCgl4NI0uxbsER
