language: ruby

rvm:
  - ruby-2.3.0
  - 2.1.2
  - 2.1.1
  - 2.1.0

before_install:
  - gem install bundler
  - rm -f .git/index.lock

script: "bundle exec rake spec:with_coveralls"

notifications:
  slack: sachin21dev:3pEyff2UFnoCgl4NI0uxbsER
