language: ruby

rvm:
  - 2.1.2
  - 2.1.1
  - 2.1.0
  - 1.9.3-p392
  - 1.9.3-p429
  - 1.9.3-p448

script: "bundle exec rake spec:with_coveralls"

notifications:
  slack: sachin21dev:3pEyff2UFnoCgl4NI0uxbsER
